name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: pandoc/latex

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: mkdir out

    - name: build
      run: | 
        make
        make biber
        make
        make
